// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.20.0--rc1
// source: protocol/comms.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_UKNOWN_PACKET_TYPE PacketType = 0
	PacketType_MESSAGE            PacketType = 1
	PacketType_PING               PacketType = 2
	PacketType_PONG               PacketType = 3
	PacketType_SUSPEND_RELAY      PacketType = 4
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "UKNOWN_PACKET_TYPE",
		1: "MESSAGE",
		2: "PING",
		3: "PONG",
		4: "SUSPEND_RELAY",
	}
	PacketType_value = map[string]int32{
		"UKNOWN_PACKET_TYPE": 0,
		"MESSAGE":            1,
		"PING":               2,
		"PONG":               3,
		"SUSPEND_RELAY":      4,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_comms_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_protocol_comms_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{0}
}

type PayloadEncoding int32

const (
	PayloadEncoding_BYTES  PayloadEncoding = 0
	PayloadEncoding_STRING PayloadEncoding = 1
	PayloadEncoding_JSON   PayloadEncoding = 2
)

// Enum value maps for PayloadEncoding.
var (
	PayloadEncoding_name = map[int32]string{
		0: "BYTES",
		1: "STRING",
		2: "JSON",
	}
	PayloadEncoding_value = map[string]int32{
		"BYTES":  0,
		"STRING": 1,
		"JSON":   2,
	}
)

func (x PayloadEncoding) Enum() *PayloadEncoding {
	p := new(PayloadEncoding)
	*p = x
	return p
}

func (x PayloadEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_comms_proto_enumTypes[1].Descriptor()
}

func (PayloadEncoding) Type() protoreflect.EnumType {
	return &file_protocol_comms_proto_enumTypes[1]
}

func (x PayloadEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadEncoding.Descriptor instead.
func (PayloadEncoding) EnumDescriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{1}
}

type ProfileData_ProfileType int32

const (
	ProfileData_DEPLOYED ProfileData_ProfileType = 0
	ProfileData_LOCAL    ProfileData_ProfileType = 1
)

// Enum value maps for ProfileData_ProfileType.
var (
	ProfileData_ProfileType_name = map[int32]string{
		0: "DEPLOYED",
		1: "LOCAL",
	}
	ProfileData_ProfileType_value = map[string]int32{
		"DEPLOYED": 0,
		"LOCAL":    1,
	}
)

func (x ProfileData_ProfileType) Enum() *ProfileData_ProfileType {
	p := new(ProfileData_ProfileType)
	*p = x
	return p
}

func (x ProfileData_ProfileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileData_ProfileType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_comms_proto_enumTypes[2].Descriptor()
}

func (ProfileData_ProfileType) Type() protoreflect.EnumType {
	return &file_protocol_comms_proto_enumTypes[2]
}

func (x ProfileData_ProfileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileData_ProfileType.Descriptor instead.
func (ProfileData_ProfileType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{1, 0}
}

type MessageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room     string          `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Dst      [][]byte        `protobuf:"bytes,2,rep,name=dst,proto3" json:"dst,omitempty"`
	Payload  []byte          `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Encoding PayloadEncoding `protobuf:"varint,4,opt,name=encoding,proto3,enum=PayloadEncoding" json:"encoding,omitempty"`
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{0}
}

func (x *MessageData) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *MessageData) GetDst() [][]byte {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *MessageData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageData) GetEncoding() PayloadEncoding {
	if x != nil {
		return x.Encoding
	}
	return PayloadEncoding_BYTES
}

type ProfileData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileVersion string                  `protobuf:"bytes,1,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	UserId         string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileType    ProfileData_ProfileType `protobuf:"varint,3,opt,name=profile_type,json=profileType,proto3,enum=ProfileData_ProfileType" json:"profile_type,omitempty"`
}

func (x *ProfileData) Reset() {
	*x = ProfileData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileData) ProtoMessage() {}

func (x *ProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileData.ProtoReflect.Descriptor instead.
func (*ProfileData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileData) GetProfileVersion() string {
	if x != nil {
		return x.ProfileVersion
	}
	return ""
}

func (x *ProfileData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileData) GetProfileType() ProfileData_ProfileType {
	if x != nil {
		return x.ProfileType
	}
	return ProfileData_DEPLOYED
}

type ProfileRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileVersion string `protobuf:"bytes,1,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	UserId         string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ProfileRequestData) Reset() {
	*x = ProfileRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequestData) ProtoMessage() {}

func (x *ProfileRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequestData.ProtoReflect.Descriptor instead.
func (*ProfileRequestData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileRequestData) GetProfileVersion() string {
	if x != nil {
		return x.ProfileVersion
	}
	return ""
}

func (x *ProfileRequestData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProfileResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SerializedProfile string `protobuf:"bytes,1,opt,name=serialized_profile,json=serializedProfile,proto3" json:"serialized_profile,omitempty"`
}

func (x *ProfileResponseData) Reset() {
	*x = ProfileResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponseData) ProtoMessage() {}

func (x *ProfileResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponseData.ProtoReflect.Descriptor instead.
func (*ProfileResponseData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileResponseData) GetSerializedProfile() string {
	if x != nil {
		return x.SerializedProfile
	}
	return ""
}

type ChatData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text      string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ChatData) Reset() {
	*x = ChatData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatData) ProtoMessage() {}

func (x *ChatData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatData.ProtoReflect.Descriptor instead.
func (*ChatData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{4}
}

func (x *ChatData) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SceneData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SceneId string `protobuf:"bytes,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	Text    string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *SceneData) Reset() {
	*x = SceneData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneData) ProtoMessage() {}

func (x *SceneData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneData.ProtoReflect.Descriptor instead.
func (*SceneData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{5}
}

func (x *SceneData) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *SceneData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type VoiceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncodedSamples []byte `protobuf:"bytes,1,opt,name=encoded_samples,json=encodedSamples,proto3" json:"encoded_samples,omitempty"`
	Index          uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *VoiceData) Reset() {
	*x = VoiceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoiceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceData) ProtoMessage() {}

func (x *VoiceData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceData.ProtoReflect.Descriptor instead.
func (*VoiceData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{6}
}

func (x *VoiceData) GetEncodedSamples() []byte {
	if x != nil {
		return x.EncodedSamples
	}
	return nil
}

func (x *VoiceData) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequenceId       uint32 `protobuf:"varint,1,opt,name=sequenceId,proto3" json:"sequenceId,omitempty"`
	InstanceId       uint32 `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Timestamp        uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Src              string `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	Subtype          string `protobuf:"bytes,5,opt,name=subtype,proto3" json:"subtype,omitempty"`
	DiscardOlderThan int32  `protobuf:"varint,6,opt,name=discardOlderThan,proto3" json:"discardOlderThan,omitempty"`
	ExpireTime       int32  `protobuf:"varint,7,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Data             []byte `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{7}
}

func (x *Packet) GetSequenceId() uint32 {
	if x != nil {
		return x.SequenceId
	}
	return 0
}

func (x *Packet) GetInstanceId() uint32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *Packet) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Packet) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Packet) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *Packet) GetDiscardOlderThan() int32 {
	if x != nil {
		return x.DiscardOlderThan
	}
	return 0
}

func (x *Packet) GetExpireTime() int32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PositionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionX float32 `protobuf:"fixed32,1,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY float32 `protobuf:"fixed32,2,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionZ float32 `protobuf:"fixed32,3,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	RotationX float32 `protobuf:"fixed32,4,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY float32 `protobuf:"fixed32,5,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ float32 `protobuf:"fixed32,6,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	RotationW float32 `protobuf:"fixed32,7,opt,name=rotation_w,json=rotationW,proto3" json:"rotation_w,omitempty"`
	Time      float64 `protobuf:"fixed64,8,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *PositionData) Reset() {
	*x = PositionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_comms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionData) ProtoMessage() {}

func (x *PositionData) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_comms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionData.ProtoReflect.Descriptor instead.
func (*PositionData) Descriptor() ([]byte, []int) {
	return file_protocol_comms_proto_rawDescGZIP(), []int{8}
}

func (x *PositionData) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PositionData) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *PositionData) GetPositionZ() float32 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *PositionData) GetRotationX() float32 {
	if x != nil {
		return x.RotationX
	}
	return 0
}

func (x *PositionData) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

func (x *PositionData) GetRotationZ() float32 {
	if x != nil {
		return x.RotationZ
	}
	return 0
}

func (x *PositionData) GetRotationW() float32 {
	if x != nil {
		return x.RotationW
	}
	return 0
}

func (x *PositionData) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_protocol_comms_proto protoreflect.FileDescriptor

var file_protocol_comms_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x22, 0xb4, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x26, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x22, 0x56, 0x0a, 0x12, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x44, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x3d, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3a, 0x0a, 0x09, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x4a, 0x0a, 0x09, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x27, 0x0a, 0x0f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x65, 0x6e, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22,
	0xf2, 0x01, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x4f,
	0x6c, 0x64, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x4f, 0x6c, 0x64, 0x65, 0x72, 0x54, 0x68, 0x61, 0x6e,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xfb, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x59, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5a, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x7a, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5a, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x77, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x2a, 0x58, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x12, 0x55, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x50, 0x41, 0x43, 0x4b, 0x45,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53,
	0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x55, 0x53,
	0x50, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x10, 0x04, 0x2a, 0x32, 0x0a, 0x0f,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x09, 0x0a, 0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54,
	0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x02,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x65, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x61, 0x6e, 0x64, 0x2f, 0x6e, 0x61, 0x74, 0x73,
	0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_comms_proto_rawDescOnce sync.Once
	file_protocol_comms_proto_rawDescData = file_protocol_comms_proto_rawDesc
)

func file_protocol_comms_proto_rawDescGZIP() []byte {
	file_protocol_comms_proto_rawDescOnce.Do(func() {
		file_protocol_comms_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_comms_proto_rawDescData)
	})
	return file_protocol_comms_proto_rawDescData
}

var file_protocol_comms_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protocol_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protocol_comms_proto_goTypes = []interface{}{
	(PacketType)(0),              // 0: PacketType
	(PayloadEncoding)(0),         // 1: PayloadEncoding
	(ProfileData_ProfileType)(0), // 2: ProfileData.ProfileType
	(*MessageData)(nil),          // 3: MessageData
	(*ProfileData)(nil),          // 4: ProfileData
	(*ProfileRequestData)(nil),   // 5: ProfileRequestData
	(*ProfileResponseData)(nil),  // 6: ProfileResponseData
	(*ChatData)(nil),             // 7: ChatData
	(*SceneData)(nil),            // 8: SceneData
	(*VoiceData)(nil),            // 9: VoiceData
	(*Packet)(nil),               // 10: Packet
	(*PositionData)(nil),         // 11: PositionData
}
var file_protocol_comms_proto_depIdxs = []int32{
	1, // 0: MessageData.encoding:type_name -> PayloadEncoding
	2, // 1: ProfileData.profile_type:type_name -> ProfileData.ProfileType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_comms_proto_init() }
func file_protocol_comms_proto_init() {
	if File_protocol_comms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_comms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoiceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_comms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_comms_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_comms_proto_goTypes,
		DependencyIndexes: file_protocol_comms_proto_depIdxs,
		EnumInfos:         file_protocol_comms_proto_enumTypes,
		MessageInfos:      file_protocol_comms_proto_msgTypes,
	}.Build()
	File_protocol_comms_proto = out.File
	file_protocol_comms_proto_rawDesc = nil
	file_protocol_comms_proto_goTypes = nil
	file_protocol_comms_proto_depIdxs = nil
}
